# Generated by Django 3.0.5 on 2020-04-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Squares',
            new_name='Square',
        ),
    ]
